### ISSUE TITLE
Support `.pcss` file extension

### ISSUE THREAD

**Issue by AlexWayfer** [csstools/postcss-custom-selectors#47]
Hello.

I've faced a problem: when I had `selectors.pcss` file with custom selectors and `importFrom` option — it didn't work, but there were no errors or warnings, nothing. Then I've tried to change file extension to `.css` — and it started work! And even errors about non-existent files.

So:

1. I think this plugin should support `.pcss` file extension (syntax of PostCSS with plugins not always CSS compatible).
2. There should be errors for "ignored" (non-supported) files (formats, file extensions) which specified in the `importFrom` option (and maybe somewhere else).

**Comment by romainmenke** [comment]
`importFrom` will be removed in future versions of this plugin as it is a non-standard feature.

Read more about this here : https://github.com/csstools/postcss-plugins/discussions/192
